# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/n/projects/streamer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/n/projects/streamer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/n/projects/streamer/CMakeFiles /mnt/n/projects/streamer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/n/projects/streamer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/n/projects/streamer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indicators

# Build rule for target.
indicators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 indicators
.PHONY : indicators

# fast build rule for target.
indicators/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/build
.PHONY : indicators/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

benchmark.o: benchmark.c.o
.PHONY : benchmark.o

# target to build an object file
benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.o
.PHONY : benchmark.c.o

benchmark.i: benchmark.c.i
.PHONY : benchmark.i

# target to preprocess a source file
benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.i
.PHONY : benchmark.c.i

benchmark.s: benchmark.c.s
.PHONY : benchmark.s

# target to generate assembly for a file
benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.s
.PHONY : benchmark.c.s

src/atr.o: src/atr.c.o
.PHONY : src/atr.o

# target to build an object file
src/atr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/atr.c.o
.PHONY : src/atr.c.o

src/atr.i: src/atr.c.i
.PHONY : src/atr.i

# target to preprocess a source file
src/atr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/atr.c.i
.PHONY : src/atr.c.i

src/atr.s: src/atr.c.s
.PHONY : src/atr.s

# target to generate assembly for a file
src/atr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/atr.c.s
.PHONY : src/atr.c.s

src/bollinger.o: src/bollinger.c.o
.PHONY : src/bollinger.o

# target to build an object file
src/bollinger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/bollinger.c.o
.PHONY : src/bollinger.c.o

src/bollinger.i: src/bollinger.c.i
.PHONY : src/bollinger.i

# target to preprocess a source file
src/bollinger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/bollinger.c.i
.PHONY : src/bollinger.c.i

src/bollinger.s: src/bollinger.c.s
.PHONY : src/bollinger.s

# target to generate assembly for a file
src/bollinger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/bollinger.c.s
.PHONY : src/bollinger.c.s

src/cci.o: src/cci.c.o
.PHONY : src/cci.o

# target to build an object file
src/cci.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/cci.c.o
.PHONY : src/cci.c.o

src/cci.i: src/cci.c.i
.PHONY : src/cci.i

# target to preprocess a source file
src/cci.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/cci.c.i
.PHONY : src/cci.c.i

src/cci.s: src/cci.c.s
.PHONY : src/cci.s

# target to generate assembly for a file
src/cci.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/cci.c.s
.PHONY : src/cci.c.s

src/ema.o: src/ema.c.o
.PHONY : src/ema.o

# target to build an object file
src/ema.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/ema.c.o
.PHONY : src/ema.c.o

src/ema.i: src/ema.c.i
.PHONY : src/ema.i

# target to preprocess a source file
src/ema.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/ema.c.i
.PHONY : src/ema.c.i

src/ema.s: src/ema.c.s
.PHONY : src/ema.s

# target to generate assembly for a file
src/ema.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/ema.c.s
.PHONY : src/ema.c.s

src/keltner.o: src/keltner.c.o
.PHONY : src/keltner.o

# target to build an object file
src/keltner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/keltner.c.o
.PHONY : src/keltner.c.o

src/keltner.i: src/keltner.c.i
.PHONY : src/keltner.i

# target to preprocess a source file
src/keltner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/keltner.c.i
.PHONY : src/keltner.c.i

src/keltner.s: src/keltner.c.s
.PHONY : src/keltner.s

# target to generate assembly for a file
src/keltner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/keltner.c.s
.PHONY : src/keltner.c.s

src/linreg_slope.o: src/linreg_slope.c.o
.PHONY : src/linreg_slope.o

# target to build an object file
src/linreg_slope.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/linreg_slope.c.o
.PHONY : src/linreg_slope.c.o

src/linreg_slope.i: src/linreg_slope.c.i
.PHONY : src/linreg_slope.i

# target to preprocess a source file
src/linreg_slope.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/linreg_slope.c.i
.PHONY : src/linreg_slope.c.i

src/linreg_slope.s: src/linreg_slope.c.s
.PHONY : src/linreg_slope.s

# target to generate assembly for a file
src/linreg_slope.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/linreg_slope.c.s
.PHONY : src/linreg_slope.c.s

src/macd.o: src/macd.c.o
.PHONY : src/macd.o

# target to build an object file
src/macd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/macd.c.o
.PHONY : src/macd.c.o

src/macd.i: src/macd.c.i
.PHONY : src/macd.i

# target to preprocess a source file
src/macd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/macd.c.i
.PHONY : src/macd.c.i

src/macd.s: src/macd.c.s
.PHONY : src/macd.s

# target to generate assembly for a file
src/macd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/macd.c.s
.PHONY : src/macd.c.s

src/mfi.o: src/mfi.c.o
.PHONY : src/mfi.o

# target to build an object file
src/mfi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/mfi.c.o
.PHONY : src/mfi.c.o

src/mfi.i: src/mfi.c.i
.PHONY : src/mfi.i

# target to preprocess a source file
src/mfi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/mfi.c.i
.PHONY : src/mfi.c.i

src/mfi.s: src/mfi.c.s
.PHONY : src/mfi.s

# target to generate assembly for a file
src/mfi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/mfi.c.s
.PHONY : src/mfi.c.s

src/obv.o: src/obv.c.o
.PHONY : src/obv.o

# target to build an object file
src/obv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/obv.c.o
.PHONY : src/obv.c.o

src/obv.i: src/obv.c.i
.PHONY : src/obv.i

# target to preprocess a source file
src/obv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/obv.c.i
.PHONY : src/obv.c.i

src/obv.s: src/obv.c.s
.PHONY : src/obv.s

# target to generate assembly for a file
src/obv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/obv.c.s
.PHONY : src/obv.c.s

src/rsi.o: src/rsi.c.o
.PHONY : src/rsi.o

# target to build an object file
src/rsi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/rsi.c.o
.PHONY : src/rsi.c.o

src/rsi.i: src/rsi.c.i
.PHONY : src/rsi.i

# target to preprocess a source file
src/rsi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/rsi.c.i
.PHONY : src/rsi.c.i

src/rsi.s: src/rsi.c.s
.PHONY : src/rsi.s

# target to generate assembly for a file
src/rsi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/rsi.c.s
.PHONY : src/rsi.c.s

src/sma.o: src/sma.c.o
.PHONY : src/sma.o

# target to build an object file
src/sma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/sma.c.o
.PHONY : src/sma.c.o

src/sma.i: src/sma.c.i
.PHONY : src/sma.i

# target to preprocess a source file
src/sma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/sma.c.i
.PHONY : src/sma.c.i

src/sma.s: src/sma.c.s
.PHONY : src/sma.s

# target to generate assembly for a file
src/sma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/sma.c.s
.PHONY : src/sma.c.s

src/stochastic.o: src/stochastic.c.o
.PHONY : src/stochastic.o

# target to build an object file
src/stochastic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/stochastic.c.o
.PHONY : src/stochastic.c.o

src/stochastic.i: src/stochastic.c.i
.PHONY : src/stochastic.i

# target to preprocess a source file
src/stochastic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/stochastic.c.i
.PHONY : src/stochastic.c.i

src/stochastic.s: src/stochastic.c.s
.PHONY : src/stochastic.s

# target to generate assembly for a file
src/stochastic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/stochastic.c.s
.PHONY : src/stochastic.c.s

src/supertrend.o: src/supertrend.c.o
.PHONY : src/supertrend.o

# target to build an object file
src/supertrend.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/supertrend.c.o
.PHONY : src/supertrend.c.o

src/supertrend.i: src/supertrend.c.i
.PHONY : src/supertrend.i

# target to preprocess a source file
src/supertrend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/supertrend.c.i
.PHONY : src/supertrend.c.i

src/supertrend.s: src/supertrend.c.s
.PHONY : src/supertrend.s

# target to generate assembly for a file
src/supertrend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/supertrend.c.s
.PHONY : src/supertrend.c.s

src/utils/deque.o: src/utils/deque.c.o
.PHONY : src/utils/deque.o

# target to build an object file
src/utils/deque.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/deque.c.o
.PHONY : src/utils/deque.c.o

src/utils/deque.i: src/utils/deque.c.i
.PHONY : src/utils/deque.i

# target to preprocess a source file
src/utils/deque.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/deque.c.i
.PHONY : src/utils/deque.c.i

src/utils/deque.s: src/utils/deque.c.s
.PHONY : src/utils/deque.s

# target to generate assembly for a file
src/utils/deque.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/deque.c.s
.PHONY : src/utils/deque.c.s

src/utils/rw_minmax.o: src/utils/rw_minmax.c.o
.PHONY : src/utils/rw_minmax.o

# target to build an object file
src/utils/rw_minmax.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/rw_minmax.c.o
.PHONY : src/utils/rw_minmax.c.o

src/utils/rw_minmax.i: src/utils/rw_minmax.c.i
.PHONY : src/utils/rw_minmax.i

# target to preprocess a source file
src/utils/rw_minmax.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/rw_minmax.c.i
.PHONY : src/utils/rw_minmax.c.i

src/utils/rw_minmax.s: src/utils/rw_minmax.c.s
.PHONY : src/utils/rw_minmax.s

# target to generate assembly for a file
src/utils/rw_minmax.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/utils/rw_minmax.c.s
.PHONY : src/utils/rw_minmax.c.s

src/williams_r.o: src/williams_r.c.o
.PHONY : src/williams_r.o

# target to build an object file
src/williams_r.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/williams_r.c.o
.PHONY : src/williams_r.c.o

src/williams_r.i: src/williams_r.c.i
.PHONY : src/williams_r.i

# target to preprocess a source file
src/williams_r.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/williams_r.c.i
.PHONY : src/williams_r.c.i

src/williams_r.s: src/williams_r.c.s
.PHONY : src/williams_r.s

# target to generate assembly for a file
src/williams_r.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indicators.dir/build.make CMakeFiles/indicators.dir/src/williams_r.c.s
.PHONY : src/williams_r.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... benchmark"
	@echo "... indicators"
	@echo "... benchmark.o"
	@echo "... benchmark.i"
	@echo "... benchmark.s"
	@echo "... src/atr.o"
	@echo "... src/atr.i"
	@echo "... src/atr.s"
	@echo "... src/bollinger.o"
	@echo "... src/bollinger.i"
	@echo "... src/bollinger.s"
	@echo "... src/cci.o"
	@echo "... src/cci.i"
	@echo "... src/cci.s"
	@echo "... src/ema.o"
	@echo "... src/ema.i"
	@echo "... src/ema.s"
	@echo "... src/keltner.o"
	@echo "... src/keltner.i"
	@echo "... src/keltner.s"
	@echo "... src/linreg_slope.o"
	@echo "... src/linreg_slope.i"
	@echo "... src/linreg_slope.s"
	@echo "... src/macd.o"
	@echo "... src/macd.i"
	@echo "... src/macd.s"
	@echo "... src/mfi.o"
	@echo "... src/mfi.i"
	@echo "... src/mfi.s"
	@echo "... src/obv.o"
	@echo "... src/obv.i"
	@echo "... src/obv.s"
	@echo "... src/rsi.o"
	@echo "... src/rsi.i"
	@echo "... src/rsi.s"
	@echo "... src/sma.o"
	@echo "... src/sma.i"
	@echo "... src/sma.s"
	@echo "... src/stochastic.o"
	@echo "... src/stochastic.i"
	@echo "... src/stochastic.s"
	@echo "... src/supertrend.o"
	@echo "... src/supertrend.i"
	@echo "... src/supertrend.s"
	@echo "... src/utils/deque.o"
	@echo "... src/utils/deque.i"
	@echo "... src/utils/deque.s"
	@echo "... src/utils/rw_minmax.o"
	@echo "... src/utils/rw_minmax.i"
	@echo "... src/utils/rw_minmax.s"
	@echo "... src/williams_r.o"
	@echo "... src/williams_r.i"
	@echo "... src/williams_r.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/n/projects/streamer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

